spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: lwc19970820
    url: jdbc:mysql://101.133.170.240/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null

server:
  context-path: /sell



logging:
  pattern:
    console: "%d - %msg%n"
  file:  D:\hello\sell.log
  level:
    com.imooc.sell.service.LoggerTest: debug


#
#wechat:
#  mpAppId: wx69934a7f0d1dab12
#  mpAppSecret: 723b060e07154463523ed9ef5500ea18
