spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.2.153/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell



logging:
  pattern:
    console: "%d - %msg%n"
  file:  D:\hello\sell.log
  level:
    com.imooc.sell.service.LoggerTest: debug
